[project]
name = "TelegramCrawler"
version = "0.1.0"
description = "A containerized FastAPI microservice that provides structured telegram scraping through telethon"
requires-python = ">=3.11"
dependencies = [
    "fastapi >= 0.141.1",
    "python-dotenv>=1.2.3",
    "telethon>=1.44.0",
    "uvicorn[standard]>=0.52.4",
    "vadersentiment>=3.3.2",
]
